// 高质量词根词缀数据库 - 基于权威词根词典整理
const ComprehensiveRootData = {
    // 常用前缀 (50个)
    prefixes: {
        "a-": "不，无",
        "ab-": "离开，脱离", 
        "ad-": "向，朝",
        "ante-": "前，在前",
        "anti-": "反对，抗",
        "auto-": "自动，自己",
        "be-": "使成为",
        "bi-": "二，双",
        "circum-": "环绕，周围",
        "co-": "共同，一起",
        "con-": "共同，一起",
        "contra-": "反对，相反",
        "counter-": "反对，相反",
        "de-": "去除，向下",
        "dis-": "不，分离",
        "em-": "使成为",
        "en-": "使成为",
        "ex-": "向外，前任",
        "extra-": "超出，在外",
        "fore-": "前面，预先",
        "hyper-": "超过，过多",
        "hypo-": "下，低",
        "il-": "不，非",
        "im-": "不，非",
        "in-": "不，非；向内",
        "inter-": "在...之间",
        "intra-": "在内，内部",
        "ir-": "不，非",
        "macro-": "大，宏观",
        "mal-": "坏，恶",
        "micro-": "小，微观",
        "mis-": "错误，坏",
        "mono-": "单一",
        "multi-": "多",
        "neo-": "新的",
        "non-": "不，非",
        "out-": "超过，向外",
        "over-": "在...之上",
        "para-": "旁边，类似",
        "post-": "后，后面",
        "pre-": "预先，在前",
        "pro-": "支持，向前",
        "re-": "再，重新",
        "semi-": "半",
        "sub-": "在下，次",
        "super-": "超，超级",
        "trans-": "穿过，转换",
        "tri-": "三",
        "ultra-": "极端，超",
        "un-": "不，非",
        "under-": "在...下"
    },
    
    // 常用后缀 (60个)
    suffixes: {
        "-able": "能够的",
        "-ible": "能够的",
        "-acy": "状态，性质",
        "-age": "行为，状态",
        "-al": "...的",
        "-ance": "状态，性质",
        "-ant": "...的人/物",
        "-ary": "与...有关的",
        "-ate": "动词/形容词后缀",
        "-ation": "行为，过程",
        "-dom": "状态，领域",
        "-ed": "过去式/形容词",
        "-ence": "状态，性质",
        "-ent": "形容词后缀",
        "-er": "表示人或物",
        "-ery": "场所，行为",
        "-ess": "女性",
        "-est": "最高级",
        "-ful": "充满的",
        "-hood": "状态，时期",
        "-ic": "...的",
        "-ify": "使成为",
        "-ing": "进行时/名词",
        "-ion": "名词后缀",
        "-ish": "有...性质的",
        "-ism": "名词后缀",
        "-ist": "表示人",
        "-ity": "名词后缀",
        "-ive": "有...倾向",
        "-ize": "使成为",
        "-less": "没有的",
        "-ly": "副词后缀",
        "-ment": "名词后缀",
        "-ness": "名词后缀",
        "-or": "表示人或物",
        "-ory": "与...有关的",
        "-ous": "具有...性质",
        "-ship": "状态，关系",
        "-sion": "名词后缀",
        "-tion": "名词后缀",
        "-ward": "向...方向",
        "-wise": "在...方面",
        "-y": "形容词/名词后缀"
    },
    
    // 核心词根 (200个)
    roots: {
        // 基础动作
        "act": "做，行动",
        "ag": "做，驱动", 
        "duc": "引导",
        "fac": "做",
        "fer": "带来",
        "ject": "投掷",
        "mit": "送",
        "mov": "移动",
        "port": "带来",
        "pos": "放置",
        "press": "压",
        "tract": "拉",
        "ven": "来",
        "vers": "转",
        "vert": "转",
        
        // 感知认知
        "aud": "听",
        "vid": "看",
        "vis": "看",
        "spect": "看",
        "scop": "看",
        "sent": "感觉",
        "sens": "感觉",
        "sci": "知道",
        "cogn": "知道",
        "ment": "心智",
        "memor": "记忆",
        "psych": "心理",
        
        // 交流表达
        "dict": "说",
        "log": "说话",
        "loqu": "说话",
        "voc": "声音",
        "phon": "声音",
        "graph": "写",
        "script": "写",
        "lect": "选择，读",
        "leg": "选择，读",
        
        // 身体部位
        "cap": "头",
        "capit": "头",
        "corp": "身体",
        "man": "手",
        "manu": "手",
        "ped": "脚",
        "pod": "脚",
        "cord": "心",
        "dent": "牙齿",
        "ocul": "眼睛",
        "aur": "耳朵",
        
        // 生命自然
        "bio": "生命",
        "viv": "活",
        "vit": "生命",
        "mort": "死",
        "anim": "生命",
        "spir": "呼吸",
        "sanguin": "血",
        "aqua": "水",
        "aer": "空气",
        "terr": "土地",
        "geo": "地球",
        "sol": "太阳",
        "lun": "月亮",
        
        // 时间空间
        "chron": "时间",
        "temp": "时间",
        "ann": "年",
        "loc": "地方",
        "situ": "位置",
        "reg": "区域",
        "urb": "城市",
        "mont": "山",
        "mar": "海",
        
        // 数量大小
        "uni": "一",
        "mono": "一",
        "bi": "二",
        "du": "二",
        "tri": "三",
        "quad": "四",
        "quint": "五",
        "sex": "六",
        "sept": "七",
        "oct": "八",
        "nov": "九",
        "dec": "十",
        "cent": "百",
        "mill": "千",
        "magn": "大",
        "max": "最大",
        "min": "小",
        "micro": "微小",
        
        // 形状属性
        "form": "形状",
        "morph": "形状",
        "struct": "建造",
        "rect": "直",
        "curv": "弯曲",
        "circ": "圆",
        "spher": "球",
        "ang": "角",
        "lin": "线",
        
        // 颜色
        "alb": "白",
        "nigr": "黑",
        "rub": "红",
        "flav": "黄",
        "vir": "绿",
        "caer": "蓝",
        
        // 物质材料
        "aqu": "水",
        "ign": "火",
        "lign": "木",
        "ferr": "铁",
        "aur": "金",
        "argent": "银",
        "plumb": "铅",
        "carbon": "碳",
        
        // 学科技术
        "techn": "技术",
        "mech": "机械",
        "electr": "电",
        "phys": "物理",
        "chem": "化学",
        "math": "数学",
        "geometr": "几何",
        "astro": "星星",
        "cosm": "宇宙",
        
        // 社会关系
        "soci": "社会",
        "popul": "人民",
        "civ": "公民",
        "polit": "政治",
        "leg": "法律",
        "jur": "法律",
        "just": "正义",
        "liber": "自由",
        "serv": "服务",
        "domin": "统治",
        
        // 家庭关系
        "famili": "家庭",
        "matr": "母亲",
        "patr": "父亲",
        "fili": "儿子",
        "frat": "兄弟",
        "soror": "姐妹",
        "gener": "产生",
        
        // 情感状态
        "am": "爱",
        "od": "恨",
        "gaud": "快乐",
        "dolor": "痛苦",
        "trist": "悲伤",
        "tim": "恐惧",
        "aud": "勇敢",
        "sper": "希望",
        "fid": "信任",
        
        // 价值判断
        "bon": "好",
        "mal": "坏",
        "bene": "善",
        "male": "恶",
        "ver": "真实",
        "fals": "虚假",
        "just": "正义",
        "rect": "正确",
        "err": "错误",
        
        // 密码学计算
        "cipher": "密码，零",
        "crypt": "隐藏，秘密",
        "cod": "代码",
        "sign": "符号，标志",
        "numer": "数字",
        "calcul": "计算",
        "comput": "计算",
        "digit": "手指，数字",
        
        // 医学生物
        "medic": "医学",
        "san": "健康",
        "path": "疾病",
        "therm": "热",
        "febr": "发热",
        "cardio": "心脏",
        "gastro": "胃",
        "neuro": "神经",
        "osteo": "骨",
        "derm": "皮肤",
        
        // 运动变化
        "mob": "移动",
        "mot": "运动",
        "curr": "跑",
        "flu": "流",
        "vol": "飞",
        "salt": "跳",
        "ced": "走",
        "grad": "步骤",
        "migr": "迁移",
        
        // 连接分离
        "junct": "连接",
        "lig": "绑定",
        "nect": "连接",
        "solv": "松开",
        "lut": "松开",
        "rupt": "破裂",
        "fract": "破碎",
        "sect": "切",
        "cis": "切",
        "div": "分开"
    }
};

// 自动合并到现有系统
if (typeof EnhancedRootAnalyzer !== 'undefined') {
    Object.assign(EnhancedRootAnalyzer.prefixes, ComprehensiveRootData.prefixes);
    Object.assign(EnhancedRootAnalyzer.suffixes, ComprehensiveRootData.suffixes);
    Object.assign(EnhancedRootAnalyzer.roots, ComprehensiveRootData.roots);
    
    console.log('综合词根数据库已加载:');
    console.log('- 前缀:', Object.keys(ComprehensiveRootData.prefixes).length);
    console.log('- 后缀:', Object.keys(ComprehensiveRootData.suffixes).length);
    console.log('- 词根:', Object.keys(ComprehensiveRootData.roots).length);
    console.log('- 总计:', Object.keys(EnhancedRootAnalyzer.prefixes).length + 
                           Object.keys(EnhancedRootAnalyzer.suffixes).length + 
                           Object.keys(EnhancedRootAnalyzer.roots).length);
}